source 'https://rubygems.org'
gem 'knife-essentials'
gem 'knife-easybake', github: 'hh/knife-easybake', ref:'patch-2'
gem 'knife-acl', github: 'opscode/knife-acl', ref:'master'
gem 'mechanize'
gem 'chef'
gem 'highline'
